# Generated by Django 5.2.4 on 2025-08-11 18:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problem',
            options={'ordering': ['category__order', 'order'], 'verbose_name': 'Problem', 'verbose_name_plural': 'Problems'},
        ),
        migrations.AlterModelOptions(
            name='problemcategory',
            options={'ordering': ['order'], 'verbose_name': 'Problem Category', 'verbose_name_plural': 'Problem Categories'},
        ),
        migrations.AlterUniqueTogether(
            name='problem',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='problem',
            name='solution',
            field=models.TextField(blank=True, help_text='Reference solution for the problem'),
        ),
        migrations.AddField(
            model_name='problem',
            name='test_cases',
            field=models.TextField(default='[]', help_text='JSON array of test cases'),
        ),
        migrations.AlterField(
            model_name='problem',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='problem',
            name='input_args',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='problem',
            name='method_stub',
            field=models.TextField(default=django.utils.timezone.now, help_text='Starter code template for the problem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='problem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='tools',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='problemcategory',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='problem',
            name='is_active',
        ),
    ]
